name: Test
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      #　node_modulesのあるディレクトリに移動してください
      - name: Install dependencies
        run: |
          bun install

      #　node_modulesのあるディレクトリに移動してください
      - name: Run lint
        run: |
          bun run lint

      #　node_modulesのあるディレクトリに移動してください
      - name: Run test
        run: |
          bun test
