name: Coverage Report
on:
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # node_modulesのあるディレクトリに移動してください
      - name: Install dependencies
        run: |
          npm install

      # pull requestの時のみカバレッジレポートをコメントする
      - name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          working-directory: "."
          test-command: "npm run test:coverage"
